---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www-xiaomo-io
spec:
  secretName: www-xiaomo-io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: www.xiaomo.io
  dnsNames:
  - www.xiaomo.io