apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-traefik
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: cert@xiaomo.io
    privateKeySecretRef:
      name: letsencrypt-prod-traefik
    solvers:
      - http01:
          ingress:
            class: traefik

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www-xiaomo-io
spec:
  secretName: www-xiaomo-io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod-traefik
  commonName: www.xiaomo.io
  dnsNames:
  - www.xiaomo.io