apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: wordpress
spec:
  rules:
    - host: www.xiaomo.io
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx
              servicePort: 80