apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: blog
spec:
  gateways:
  - blog/ingressgateway
  hosts:
  - www.xiaomo.io
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: nginx.blog.svc.cluster.local
        port:
          number: 80