---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/user/wordpress
    server: 172.16.1.10

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "50Gi"
  selector:
    matchLabels:
      app: wordpress